// Generated by LiveScript 1.6.0
(function(){
  var test, compilers, CC, file;
  import$(global, require('ramda'));
  test = require('ava');
  compilers = require('../bin/compilers.js');
  CC = compilers.compile;
  file = 'filename';
  test(' compile LiveScript', async function(it){
    var compiled;
    compiled = (await CC('js', 'ls', 'a |> b', file, {
      bare: true,
      header: false
    }));
    return it.is(compiled, "b(\na);");
  });
  test(' compile Pug', async function(it){
    var compiled;
    compiled = (await CC('html', 'pug', 'p(a) text', file));
    return it.is(compiled, '<p a="a">text</p>');
  });
  test(' compile Stylus', async function(it){
    var compiled;
    compiled = (await CC('css', 'styl', "p\n  color red", file));
    return it.is(compiled, 'p {\n  color: #f00;\n}\n');
  });
  test(' compile SASS', async function(it){
    var compiled;
    compiled = (await CC('css', 'sass', "$base: red\np\n  color: $base"));
    return it.is(compiled, 'p {\n  color: red;\n}');
  });
  test(' compile SCSS', async function(it){
    var compiled;
    compiled = (await CC('css', 'scss', "$base: red;\np {color: $base;}"));
    return it.is(compiled, 'p {\n  color: red;\n}');
  });
  test(' compile Markdown', async function(it){
    var compiled;
    compiled = (await CC('html', 'md', '# Header'));
    return it.is(compiled, "<h1>Header</h1>\n");
  });
  test(' pass through', async function(it){
    var compiled;
    compiled = (await CC('xyz', 'xyz', "Quick brown"));
    return it.is(compiled, 'Quick brown');
  });
  test(' recognize its suffixes', function(it){
    var dst;
    dst = prop(0)(
    find(compose$(function(it){
      return it[1];
    }, has('pug')))(
    toPairs(compilers.formats)));
    return it.is(dst, 'html');
  });
  test(' reject unknown suffixes', function(it){
    var dst;
    dst = prop(0)(
    find(compose$(function(it){
      return it[1];
    }, has('puxx')))(
    toPairs(compilers.formats)));
    return it.falsy(dst);
  });
  test(' compile Pug with locals', async function(it){
    var compiled;
    compiled = (await CC('html', 'pug', 'p foo !{foo}', file, null, {
      foo: '!{bubu}'
    }));
    return it.is(compiled, '<p>foo !{bubu}</p>');
  });
  test(' recognize Pug options', async function(it){
    var compiled;
    compiled = (await CC('html', 'pug', '.foo(x-data)= foo', file, {
      doctype: 'html'
    }, {
      foo: 'bar'
    }));
    return it.is(compiled, '<div class="foo" x-data>bar</div>');
  });
  test(' compile Nunjucks', async function(it){
    var compiled;
    compiled = (await CC('html', 'njk', '<p>{{ "foo" + foo }}</p>', file, null, {
      foo: 'bar'
    }));
    return it.is(compiled, '<p>foobar</p>');
  });
  test(' compile Nunjucks templates', async function(it){
    var compiled;
    compiled = (await CC('html', 'njk', '<meta/>{{ x | safe }}', file, null, {
      x: '<link>data</link>'
    }));
    return it.is(compiled, '<meta/><link>data</link>');
  });
  test(' resolve local modules', function(it){
    var aaa;
    aaa = compilers.resolve('aaa');
    return it.is(aaa, 'aaa');
  });
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
  function compose$() {
    var functions = arguments;
    return function() {
      var i, result;
      result = functions[0].apply(this, arguments);
      for (i = 1; i < functions.length; ++i) {
        result = functions[i](result);
      }
      return result;
    };
  }
}).call(this);
